version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3.9-management-alpine"
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"

  redis:
    image: "redis:6.2-alpine"
    container_name: "redis"
    hostname: "redis"
    environment:
      - REDIS_PASSWORD=dev1234
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"

  celery-flower:
    image: "gregsi/latest-celery-flower-docker:latest"
    container_name: "celery-flower"
    hostname: "celery-flower"
    environment:
      - AMQP_USERNAME=guest
      - AMQP_PASSWORD=guest
      - AMQP_ADMIN_USERNAME=guest
      - AMQP_ADMIN_PASSWORD=guest
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

volumes:
  rabbitmq_data:
    driver: "local"
    name: "rabbitmq_data"
  redis_data:
    driver: "local"
    name: "redis_data"
